[tool.poetry]
name = "termslime"
version = "0.1.0"
description = ""
authors = ["Gary Zhang <garyzhang2002@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
